### ISSUE TITLE
E474: Invalid argument: wildoptions=pum,tagfile

### ISSUE THREAD

**Issue by herculeskan** [theopn/kickstart.vim#1]
First of all, I appreciate your help to the newcomers in the vim path, Everything was working well, but after a time using vim, this error jumps before start, is it there a way to fix it? 
```
Error detected while processing /home/carlos/.vimrc:
line  136:
E474: Invalid argument: wildoptions=pum,tagfile
Press ENTER or type command to continue
```

**Comment by theopn** [comment]
Hi, it looks like the version of Vim you use does not support the pum,tagfile for the wildmenu option. Can you share your Vim version (`vim --version`) and whether everything works after commenting out the line 136?

**Comment by herculeskan** [comment]
Oh, I updated and it's worked. Thank you so much, I really appreciate, this is the best vim .vimrc for beginners like me

**Comment by theopn** [comment]
Glad you like it!!
